compute_engine_instance:
  image_project: airyxos-images
  image: airyxbuild-0-4-b5
  platform: freebsd
  cpu: 8
  memory: 16G
  disk: 100

build_task:
  timeout_in: 120m
  environment:
    PKG_CONFIG_PATH: /usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig
  script:
    - pkg-static install -fy pkg && pkg update
    - pkg install -y cmake jpeg-turbo openjpeg tiff png cairo fontconfig freetype2 libX11 libXext libXfixes libXdamage mesa-libs dbus pkgconf libqtxdg sqlite3 git-tiny qt5-buildtools qt5-qmake qt5-dbus qt5-linguisttools qt5-widgets qt5-x11extras qt5-dbus glib dbus-glib libffi libfm libfm-qt menu-cache gettext-runtime icu kf5-extra-cmake-modules lxqt-build-tools kf5-ki18n kf5-plasma-framework kf5-ktexteditor qt5-testlib gmake autoconf zip bash nasm yasm autoconf213 llvm13 rust rust-cbindgen sndio node jackit libXres py38-sqlite3 v4l_compat binutils nss libvpx libnotify p5-Locale-gettext aom dav1d webp libpci ffmpeg libiconv
    - curl -Lo /usr/share/mk/airyx.app.mk https://raw.githubusercontent.com/airyxos/airyx/main/share/mk/airyx.app.mk
    - curl -Lo /usr/share/mk/airyx.common.mk https://raw.githubusercontent.com/airyxos/airyx/main/share/mk/airyx.common.mk
    - curl -Lo /usr/share/mk/airyx.framework.mk https://raw.githubusercontent.com/airyxos/airyx/main/share/mk/airyx.framework.mk
    - make prep build
  only_if: $CIRRUS_BRANCH == 'main'
  app_artifacts:
    path: "*.app.txz"
